export const RECEIPT_LIST_REQUEST = 'RECEIPT_LIST_REQUEST'
export const RECEIPT_LIST_SUCCESS = 'RECEIPT_LIST_SUCCESS'
export const RECEIPT_LIST_FAIL = 'RECEIPT_LIST_FAIL'
export const RECEIPT_LIST_RESET = 'RECEIPT_LIST_RESET'

export const RECEIPT_DETAILS_REQUEST = 'RECEIPT_DETAILS_REQUEST'
export const RECEIPT_DETAILS_SUCCESS = 'RECEIPT_DETAILS_SUCCESS'
export const RECEIPT_DETAILS_FAIL = 'RECEIPT_DETAILS_FAIL'
export const RECEIPT_DETAILS_RESET = 'RECEIPT_DETAILS_RESET'

export const RECEIPT_CREATE_REQUEST = 'RECEIPT_CREATE_REQUEST'
export const RECEIPT_CREATE_SUCCESS = 'RECEIPT_CREATE_SUCCESS'
export const RECEIPT_CREATE_FAIL = 'RECEIPT_CREATE_FAIL'
export const RECEIPT_CREATE_RESET = 'RECEIPT_CREATE_RESET'

export const RECEIPT_UPDATE_REQUEST = 'RECEIPT_UPDATE_REQUEST'
export const RECEIPT_UPDATE_SUCCESS = 'RECEIPT_UPDATE_SUCCESS'
export const RECEIPT_UPDATE_FAIL = 'RECEIPT_UPDATE_FAIL'
export const RECEIPT_UPDATE_RESET = 'RECEIPT_UPDATE_RESET'

export const RECEIPT_DELETE_REQUEST = 'RECEIPT_DELETE_REQUEST'
export const RECEIPT_DELETE_SUCCESS = 'RECEIPT_DELETE_SUCCESS'
export const RECEIPT_DELETE_FAIL = 'RECEIPT_DELETE_FAIL'


