export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'


export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'


export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const TEACHER_DETAILS_REQUEST = 'TEACHER_DETAILS_REQUEST'
export const TEACHER_DETAILS_SUCCESS = 'TEACHER_DETAILS_SUCCESS'
export const TEACHER_DETAILS_FAIL = 'TEACHER_DETAILS_FAIL'
export const TEACHER_DETAILS_RESET = 'TEACHER_DETAILS_RESET'

export const TEACHER_LIST_REQUEST = 'TEACHER_LIST_REQUEST'
export const TEACHER_LIST_SUCCESS = 'TEACHER_LIST_SUCCESS'
export const TEACHER_LIST_FAIL = 'TEACHER_LIST_FAIL'
export const TEACHER_LIST_RESET = 'TEACHER_LIST_RESET'


export const TEACHER_DELETE_REQUEST = 'TEACHER_DELETE_REQUEST'
export const TEACHER_DELETE_SUCCESS = 'TEACHER_DELETE_SUCCESS'
export const TEACHER_DELETE_FAIL = 'TEACHER_DELETE_FAIL'


export const TEACHER_UPDATE_REQUEST = 'TEACHER_UPDATE_REQUEST'
export const TEACHER_UPDATE_SUCCESS = 'TEACHER_UPDATE_SUCCESS'
export const TEACHER_UPDATE_FAIL = 'TEACHER_UPDATE_FAIL'
export const TEACHER_UPDATE_RESET = 'TEACHER_UPDATE_RESET'

export const ACCOUNTANT_DETAILS_REQUEST = 'ACCOUNTANT_DETAILS_REQUEST'
export const ACCOUNTANT_DETAILS_SUCCESS = 'ACCOUNTANT_DETAILS_SUCCESS'
export const ACCOUNTANT_DETAILS_FAIL = 'ACCOUNTANT_DETAILS_FAIL'
export const ACCOUNTANT_DETAILS_RESET = 'ACCOUNTANT_DETAILS_RESET'

export const ACCOUNTANT_LIST_REQUEST = 'ACCOUNTANT_LIST_REQUEST'
export const ACCOUNTANT_LIST_SUCCESS = 'ACCOUNTANT_LIST_SUCCESS'
export const ACCOUNTANT_LIST_FAIL = 'ACCOUNTANT_LIST_FAIL'
export const ACCOUNTANT_LIST_RESET = 'ACCOUNTANT_LIST_RESET'


export const ACCOUNTANT_DELETE_REQUEST = 'ACCOUNTANT_DELETE_REQUEST'
export const ACCOUNTANT_DELETE_SUCCESS = 'ACCOUNTANT_DELETE_SUCCESS'
export const ACCOUNTANT_DELETE_FAIL = 'ACCOUNTANT_DELETE_FAIL'


export const ACCOUNTANT_UPDATE_REQUEST = 'ACCOUNTANT_UPDATE_REQUEST'
export const ACCOUNTANT_UPDATE_SUCCESS = 'ACCOUNTANT_UPDATE_SUCCESS'
export const ACCOUNTANT_UPDATE_FAIL = 'ACCOUNTANT_UPDATE_FAIL'
export const ACCOUNTANT_UPDATE_RESET = 'ACCOUNTANT_UPDATE_RESET'
